# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ cn ]
  pull_request:
    branches: [ cn ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Deploy MDBook
      uses: XAMPPRocky/deploy-mdbook@v1.1.0
      with:
        # The github reposistory in `owner/repo` format.
        repository: longfangsong/tikv-newbie
        token: f467eaa6e117af3ecf426c0bcb072899247e1b50
